# Generated by Django 3.2.4 on 2022-05-27 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 5, 28, 2, 3, 19, 961658)),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
