# Generated by Django 3.2.4 on 2022-05-28 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 5, 29, 3, 10, 12, 963043)),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_field', to='article.article')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_field', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
