# Generated by Django 3.2.4 on 2022-06-04 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20220605_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image3',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 6, 5, 3, 19, 55, 952830)),
        ),
    ]
