# Generated by Django 3.2.4 on 2022-06-04 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20220605_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image2',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2022, 6, 5, 3, 25, 48, 440867)),
        ),
    ]
